insert into tbl_student (STUDENT_NAME,GENDER,EMAIL,MOBILE_NUMBER,INSTITUTION_CODE,AADHAR_NUM,STATE_OF_DEOMICILE,PASSWORD,CONFIRM_PASSWORD)
values("Yamuna","Female","Yamuna@27","9876543210","Jsp123",123456,"AP","Yamuna@123","Yamuna@123");

insert into tbl_institute(INSTITUTE_CODE,INSTITUTE_NAME,DISE_CODE,STATE_NAME,UNIVERSITY_NAME,UNIVERSITY_STATE,INSTITUTE_EST_CERT,UNIVERSITY_BOARD_AFFIL_CERT,PASSWORD,CONFIRM_PASSWORD)
values("Jsp456","LTI","LTI987","Karnataka","JNTUA","AP","Ins_cert","Univer_cert","Yamuna@123","Yamuna@123");

insert into tbl_ministry(MINISTRY_NAME,GENDER,EMAIL,AADHAR_NUM,MOB_NUM,PASSWORD,CONFIRM_PASSWORD);
values("Anusha","Female","Anusha@27",987665,"9876543211","ANu@123","ANu@123");

insert into tbl_state(STATE_NAME,GENDER,EMAIL,MOB_NUM,AADHAR_NUM,PASSWORD,CONFIRM_PASSWORD)
values("Ap","Female","Yamuna@123","9876543212",12345,"Yamuna@123","Yamuna@123");